### ISSUE TITLE
FirstName and FirstGuid not found

### ISSUE THREAD

**Issue by Trip-eng** [ChromaControl/BroadcastVendorExtractor#1]
the program does not find "FirstName" and "FirstGuid" in the binary from Broadcast SDK v1.8.2

**Comment by AndrewBabbitt97** [comment]
Razer changed the structure, no longer works. There's a formal process for getting GUIDs so I need to update the repo with info on that. This tool will more than likely not be updated.

**Comment by Trip-eng** [comment]
thx for information.
